require('lazy').setup({
  'tpope/vim-sleuth',

  -- require 'plugins.core.cmp',
  require 'plugins.core.conform',
  require 'plugins.core.jsx-element',
  require 'plugins.core.nvim-surround',
  require 'plugins.core.snacks',
  require 'plugins.core.telescope',
  require 'plugins.core.treesitter',
  require 'plugins.core.treesitter-context',
  require 'plugins.core.treesitter-textobjects',
  require 'plugins.core.undotree',
  require 'plugins.core.which-key',
  require 'plugins.experimental.blink',
  require 'plugins.experimental.dadbod-explorer',
  require 'plugins.experimental.incline',
  require 'plugins.experimental.karen-yank',
  require 'plugins.experimental.nvim-scissors',
  require 'plugins.experimental.overseer',
  require 'plugins.experimental.quicker',
  require 'plugins.experimental.tiny-inline-diagnostic',
  require 'plugins.experimental.yazi',
  require 'plugins.experimental.blame',
  require 'plugins.lsp.lint',
  require 'plugins.lsp.lspconfig',
  require 'plugins.lsp.tailwind-tools',
  require 'plugins.lsp.typescript-tool',
  -- require 'plugins.ui.bufferline',
  require 'plugins.ui.colorscheme',
  require 'plugins.ui.gitsigns',
  require 'plugins.ui.lualine',
  require 'plugins.ui.noice',
  require 'plugins.utils.auto-session',
  require 'plugins.utils.autopairs',
  require 'plugins.utils.debug',
  require 'plugins.utils.indent_line',
  require 'plugins.utils.obsidian',
  require 'plugins.utils.refactoring',
  require 'plugins.utils.render-markdown',
  require 'plugins.utils.todo-comments',
  require 'plugins.utils.trouble',
  require 'plugins.utils.ts-comments',
  require 'plugins.vcs.gitlab',
  require 'plugins.vcs.jj-diffconflicts',
  require 'plugins.vcs.jujutsu',
  require 'plugins.vcs.lazyjj',
}, {
  ui = {
    -- If you are using a Nerd Font: set icons to an empty table which will use the
    -- default lazy.nvim defined Nerd Font icons, otherwise define a unicode icons table
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})

-- vim: ts=2 sts=2 sw=2 et
