require('lazy').setup({
  'tpope/vim-sleuth',

  require 'plugins.auto-session',
  require 'plugins.autopairs',
  require 'plugins.cmp',
  require 'plugins.colorscheme',
  require 'plugins.conform',
  require 'plugins.debug',
  require 'plugins.gitsigns',
  require 'plugins.gitlab',
  require 'plugins.indent_line',
  require 'plugins.jj-diffconflicts',
  require 'plugins.jujutsu',
  require 'plugins.lazyjj',
  require 'plugins.lint',
  require 'plugins.lspconfig',
  require 'plugins.lualine',
  require 'plugins.noice',
  require 'plugins.nvim-surround',
  require 'plugins.obsidian',
  require 'plugins.refactoring',
  require 'plugins.render-markdown',
  require 'plugins.snacks',
  require 'plugins.tailwind-tools',
  require 'plugins.telescope',
  require 'plugins.todo-comments',
  require 'plugins.treesitter',
  require 'plugins.trouble',
  require 'plugins.ts-comments',
  require 'plugins.typescript-tool',
  require 'plugins.typr',
  require 'plugins.undotree',
  require 'plugins.which-key',
}, {
  ui = {
    -- If you are using a Nerd Font: set icons to an empty table which will use the
    -- default lazy.nvim defined Nerd Font icons, otherwise define a unicode icons table
    icons = vim.g.have_nerd_font and {} or {
      cmd = '⌘',
      config = '🛠',
      event = '📅',
      ft = '📂',
      init = '⚙',
      keys = '🗝',
      plugin = '🔌',
      runtime = '💻',
      require = '🌙',
      source = '📄',
      start = '🚀',
      task = '📌',
      lazy = '💤 ',
    },
  },
})

-- vim: ts=2 sts=2 sw=2 et
